development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME_DEV'] %>
  username: <%= ENV['USERNAME_DEV'] %>
  password: <%= ENV['PASSWORD_DEV'] %>
  host: <%= ENV['HOSTNAME_DEV'] %>
  port: <%= ENV['PORT_DEV'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME_TEST'] %>
  username: <%= ENV['USERNAME_TEST'] %>
  password: <%= ENV['PASSWORD_TEST'] %>
  host: <%= ENV['HOSTNAME_TEST'] %>
  port: <%= ENV['PORT_TEST'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
