development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['LOCAL_DEV_DB_NAME'] %>
  username: <%= ENV['LOCAL_DEV_USERNAME'] %>
  password: <%= ENV['LOCAL_DEV_PASSWORD'] %>
  host: <%= ENV['LOCAL_DEV_HOSTNAME'] %>
  port: <%= ENV['LOCAL_DEV_PORT'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['LOCAL_TEST_DB_NAME'] %>
  username: <%= ENV['LOCAL_TEST_USERNAME'] %>
  password: <%= ENV['LOCAL_TEST_PASSWORD'] %>
  host: <%= ENV['LOCAL_TEST_HOSTNAME'] %>
  port: <%= ENV['LOCAL_TEST_PORT'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
